import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import NewsletterSignup from "../components/NewsletterSignup";
import OrderSummary from "../components/OrderSummary";
import QuantitySelector from "../components/QuantitySelector";

const API_BASE_URL = import.meta.env.VITE_BACKEND_API_BASE_URL || "http://localhost:5000/api/";
export default function Cart() {
  const [items, setItems] = useState([]); const [message, setMessage] = useState("");
  useEffect(() => { fetch(`${API_BASE_URL}cart`, { credentials: "include" }).then((response) => response.ok ? response.json() : Promise.reject(new Error("Sign in to load your cart"))).then((data) => setItems(data.cart.cartItems || [])).catch((error) => setMessage(error.message)); }, []);
  const updateQuantity = async (item, quantity) => { const response = await fetch(`${API_BASE_URL}cart/items/${item._id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify({ quantity }) }); if (response.ok) setItems((await response.json()).cart.cartItems); };
  const removeItem = async (item) => { const response = await fetch(`${API_BASE_URL}cart/items/${item._id}`, { method: "DELETE", credentials: "include" }); if (response.ok) setItems((await response.json()).cart.cartItems); };
  const applyCoupon = async (code) => { const response = await fetch(`${API_BASE_URL}cart/coupon`, { method: "POST", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify({ code }) }); const data = await response.json(); if (response.ok) { setItems(data.cart.cartItems); setMessage("Coupon applied"); } else setMessage(data.message); };
  const subtotal = items.reduce((total, item) => total + Number(item.product?.sellingPrice || 0) * item.quantity, 0); const discount = Math.round(subtotal * 0.2);
  return <main className="bg-white px-4 pb-16 text-black sm:px-6 lg:px-8"><div className="mx-auto max-w-310"><nav className="flex gap-2 py-5 font-sans text-xs text-black/50"><Link to="/">Home</Link><span>›</span><span>Cart</span></nav><h1 className="font-integral text-3xl uppercase sm:text-4xl">Your Cart</h1>{message && <p className="mt-3 text-sm text-black/50">{message}</p>}{!items.length ? <p className="mt-8 rounded-2xl border border-black/10 p-8 text-center font-sans text-black/60">Your cart is empty.</p> : <div className="mt-6 grid gap-5 lg:grid-cols-[1.25fr_0.85fr]"><section className="rounded-2xl border border-black/10 p-4 sm:p-5">{items.map((item) => <article className="flex gap-3 border-b border-black/10 py-4 first:pt-0 last:border-0 last:pb-0" key={item._id}><div className="size-24 rounded-xl bg-[#f0eeed] sm:size-32">{item.product?.images?.[0] && <img alt={item.product.name} className="size-full rounded-xl object-cover" src={item.product.images[0]} />}</div><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><div><h2 className="truncate font-sans font-bold">{item.product?.name}</h2><p className="font-sans text-xs text-black/60">Size: {item.size || "Not selected"}</p><p className="font-sans text-xs text-black/60">Color: {item.color || "Not selected"}</p></div><button className="text-sm text-red-500" onClick={() => removeItem(item)} type="button">Remove</button></div><div className="mt-2 flex items-center justify-between"><strong className="font-sans text-lg">${item.product?.sellingPrice}</strong><QuantitySelector max={item.product?.stockQuantity || 99} onChange={(quantity) => updateQuantity(item, quantity)} value={item.quantity} /></div></div></article>)}</section><OrderSummary discount={discount} onApplyCoupon={applyCoupon} onCheckout={() => setMessage("Checkout requires shipping details and authentication.")} subtotal={subtotal} /></div>}</div><NewsletterSignup /></main>;
}
